- name: gem environment
  command: "{{ ruby_system_gems_executable }} environment"
  register: result

- name: gem environment result parse
  set_fact:
    result_stdout: "{{ result.stdout | from_yaml }}"

# if you build a ruby ​​from source code, the directory where the ruby
# executable binary and scripts are installed may not be included in
# the PATH of the root user.  therefore this ansible role uses the
# absolute path of gem command.
- name: executable directory
  set_fact:
    executable_directory: >-
      {{
         result_stdout["RubyGems Environment"]         |
         selectattr("EXECUTABLE DIRECTORY", "defined") |
         map(attribute="EXECUTABLE DIRECTORY")         |
         first
      }}

- debug: var=executable_directory

- name: latest rubygems-update
  become: yes
  gem:
    name: rubygems-update
    user_install: no
    include_doc: "{{ ruby_system_gems_include_doc }}"
    executable: "{{ executable_directory }}/{{ ruby_system_gems_executable }}"
    state: latest
  when: ruby_system_gems_update

- name: update rubygems
  become: yes
  command: "{{ executable_directory }}/update_rubygems"
  when: ruby_system_gems_update

- name: install system gems
  become: yes
  gem:
    name: "{{ item }}"
    user_install: no
    include_doc: "{{ ruby_system_gems_include_doc }}"
    executable: "{{ executable_directory }}/{{ ruby_system_gems_executable }}"
  with_items:
    - "{{ ruby_system_gems_install_list }}"

- name: update system gems
  become: yes
  command: "{{ executable_directory }}/{{ ruby_system_gems_executable }} update --no-user-install"
  when: ruby_system_gems_update

# Local Variables:
# indent-tabs-mode: nil
# End:
